# Nixpacks Configuration for Market Motors
# This file configures the build process for Railway deployment

[phases.setup]
nixPkgs = ["nodejs-20_x", "npm-9_x"]

[phases.install]
cmds = [
    "npm ci --prefer-offline --no-audit --no-fund",
    "npm run build:server"
]

[phases.build]
cmds = [
    "npm run build",
    "npm prune --production"
]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"
NPM_CONFIG_AUDIT = "false"
NPM_CONFIG_FUND = "false"

[staticAssets]
# Serve static assets from the dist directory
"/static" = "dist" 