# Nixpacks Configuration for Market Motors Frontend

[phases.setup]
nixPkgs = ["nodejs-20_x", "npm-9_x"]

[phases.install]
cmds = [
    "npm ci --prefer-offline --no-audit --no-fund --maxsockets=1"
]

[phases.build]
cmds = [
    "npm run build"
]

[start]
cmd = "npm run preview -- --host 0.0.0.0"

[variables]
NODE_ENV = "production"
NPM_CONFIG_AUDIT = "false"
NPM_CONFIG_FUND = "false"
NPM_CONFIG_MAXSOCKETS = "1"
NODE_OPTIONS = "--max-old-space-size=768"

[staticAssets]
# Serve static assets from the dist directory
"dist" = "/" 