# Nixpacks Configuration for Market Motors
# This file configures the build process for Railway deployment

[phases.setup]
nixPkgs = ["nodejs-20_x", "npm-9_x"]

[phases.install]
cmds = [
    "npm ci --only=production",
    "npm run build"
]

[phases.build]
cmds = [
    "echo 'Build completed successfully'"
]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "true"

[staticAssets]
# Serve static assets from the dist directory
"/static" = "dist" 